project_id = "ztqtcbzjesrkuaijmylm"

[functions.create-payment]
verify_jwt = true

[functions.create-monthly-subscription]
verify_jwt = true

[functions.payment-webhook]
verify_jwt = false

[functions.admin-create-student]
verify_jwt = true

[functions.public-checkout]
verify_jwt = false
