// Banco dinâmico de treino ACE Maricá — 1.000 questões de expansão.
// Base conceitual: ACS - AE.pdf e conteúdos já utilizados no banco.
// Não são questões oficiais.
(function(){const T=[
["Conhecimentos Específicos","Lei 11.350/2006","Segundo a Lei 11.350/2006, a atuação do Agente de Combate às Endemias está relacionada principalmente a:","C","ações de vigilância, prevenção e controle de doenças e promoção da saúde.","A","atividade exclusivamente administrativa.","B","atendimento médico e prescrição.","D","fiscalização tributária.","E","gestão financeira."],
["Conhecimentos Específicos","Atribuições do ACE","Uma atribuição compatível com o trabalho do ACE é:","A","participar de ações de vigilância, prevenção e controle de doenças.","B","prescrever medicamentos.","C","realizar cirurgias.","D","emitir diagnósticos médicos.","E","substituir a equipe de enfermagem."],
["SUS","Constituição Federal","De acordo com a Constituição Federal, a saúde é:","B","direito de todos e dever do Estado.","A","serviço exclusivo da iniciativa privada.","C","benefício condicionado à contribuição previdenciária.","D","responsabilidade apenas municipal.","E","ação limitada à assistência hospitalar."],
["SUS","Lei 8.142/90","A Lei 8.142/90 trata, entre outros temas, de:","D","participação da comunidade na gestão do SUS e transferências intergovernamentais de recursos.","A","somente licitações hospitalares.","B","somente vacinação.","C","somente vigilância sanitária.","E","somente contratos privados."],
["SUS","Conselhos e Conferências","No SUS, Conselhos de Saúde e Conferências de Saúde representam mecanismos de:","C","participação social.","A","privatização.","B","fiscalização tributária.","D","gestão empresarial privada.","E","controle exclusivo médico."],
["Educação em Saúde","Estratégias educativas","Qual recurso pode favorecer o aprendizado e o engajamento em Educação em Saúde?","E","Materiais educativos, dinâmicas participativas e tecnologias digitais.","A","Somente exposição sem interação.","B","Apenas comunicação escrita.","C","Exclusivamente atividades em grupo.","D","Somente distribuição de medicamentos."],
["Promoção da Saúde","Prevenção","Entre medidas de promoção da saúde e prevenção de doenças, destaca-se:","A","vacinação, hábitos de higiene e participação em campanhas preventivas.","B","uso de antibióticos sem prescrição.","C","evitar acompanhamento profissional.","D","substituir vacinação por remédios caseiros.","E","ignorar fatores ambientais."],
["Dengue","Aedes aegypti","Uma medida importante no controle da dengue é:","B","eliminar recipientes que possam acumular água e servir de criadouro.","A","usar inseticida como única medida.","C","eliminar somente água suja.","D","evitar toda participação comunitária.","E","considerar o vetor exclusivamente noturno."],
["Dengue","Notificação","Em contexto de vigilância epidemiológica, a notificação de casos suspeitos de dengue deve ser considerada:","D","parte das ações de vigilância e registro de agravos.","A","desnecessária.","B","exclusiva de laboratórios privados.","C","substituída por comunicação informal.","E","restrita a casos já confirmados."],
["Vacinação","PNI","A vacinação é uma estratégia central de:","C","imunização, prevenção de doenças e promoção da saúde pública.","A","tratamento cirúrgico.","B","reabilitação exclusivamente.","D","controle financeiro.","E","gestão administrativa."],
["Vacinação","Caderneta","Durante ações de acompanhamento no território, a verificação da situação vacinal pode contribuir para:","A","identificar atrasos e orientar a busca pela atualização da vacinação.","B","substituir a equipe de vacinação.","C","prescrever vacinas individualmente.","D","dispensar registros.","E","eliminar a necessidade de campanhas."],
["Visita Domiciliar","Ética e vínculo","Durante uma visita domiciliar, uma conduta adequada é:","E","respeitar privacidade, sigilo, diálogo e características da família.","A","entrar sem autorização.","B","ignorar crenças e hábitos.","C","limitar a visita a formulários.","D","divulgar informações pessoais."],
["Visita Domiciliar","Planejamento","A visita domiciliar deve ser planejada considerando:","B","prioridades de risco, vulnerabilidade e necessidades identificadas.","A","somente a distância da residência.","C","apenas a idade do morador.","D","somente horários da equipe.","E","exclusivamente registros financeiros."],
["Saneamento Básico","Saúde ambiental","Na promoção da saúde ambiental, o agente pode contribuir para:","D","identificação de fatores de risco e mobilização comunitária para saneamento e higiene.","A","fiscalização tributária.","B","licenciamento industrial.","C","prescrição de produtos químicos.","E","substituição da vigilância sanitária."],
["Epidemiologia","Vigilância","A vigilância epidemiológica utiliza informações para:","C","identificar, monitorar e orientar ações de prevenção e controle de agravos.","A","apenas calcular salários.","B","substituir a assistência médica.","D","gerar somente relatórios financeiros.","E","eliminar a necessidade de investigação."],
["COVID-19","Ações educativas","Em uma situação de transmissão de doença respiratória, ações educativas podem incluir:","A","orientações sobre higiene das mãos, prevenção e identificação de sinais de agravamento.","B","recomendação indiscriminada de antibióticos.","C","abandono da vigilância.","D","proibição de busca por atendimento.","E","substituição de avaliação profissional."],
["Alimentação e Saúde","Alimentação saudável","Uma orientação compatível com promoção da alimentação saudável é:","B","incentivar variedade, segurança alimentar e preferência por alimentos in natura ou minimamente processados.","A","recomendar dietas extremas a todos.","C","eliminar acompanhamento profissional.","D","priorizar ultraprocessados.","E","prescrever medicamentos."],
["Doenças Crônicas","Hipertensão","Em ações educativas para pessoas com hipertensão, uma orientação adequada é:","E","incentivar hábitos saudáveis e adesão ao tratamento prescrito pela equipe de saúde.","A","suspender medicamentos quando houver melhora.","B","prescrever nova medicação.","C","dispensar acompanhamento.","D","recomendar automedicação."],
["PNAB","Atenção Básica","A Atenção Básica/Primária tem como uma de suas características:","C","organização do cuidado no território e acompanhamento longitudinal dos usuários.","A","atendimento exclusivamente hospitalar.","B","ausência de vínculo.","D","atuação somente em urgências.","E","foco exclusivo em procedimentos."],
["Saúde da Mulher","Prevenção","Em ações de promoção da saúde da mulher, o agente pode:","A","orientar sobre prevenção e estimular o acompanhamento e rastreamento conforme as políticas de saúde.","B","realizar procedimentos invasivos sem habilitação.","C","prescrever exames.","D","substituir o profissional responsável.","E","ignorar atrasos de acompanhamento."]
];const C=['Em uma questão de concurso, ','Durante uma visita no território, ','Em uma ação de saúde comunitária, ','Considerando uma situação de vigilância em saúde, ','Durante uma atividade educativa, ','Em uma unidade de Atenção Básica, ','Em um cenário de prevenção de doenças, ','Durante o planejamento das ações do território, ','Considerando uma família acompanhada pela equipe, ','Em uma situação hipotética de prova, '];const out=[];for(let n=0;n<1000;n++){const t=T[n%T.length],v=Math.floor(n/T.length);const [disc,assunto,enunciado,g,cor,...pairs]=t;const alternativas={};for(let i=0;i<pairs.length;i+=2){const k=pairs[i],valor=pairs[i+1];if(['A','B','C','D','E'].includes(k)&&valor!=null)alternativas[k]=valor}alternativas[g]=cor;const ordered={A:alternativas.A,B:alternativas.B,C:alternativas.C,D:alternativas.D,E:alternativas.E};if(Object.values(ordered).some(x=>!String(x||'').trim()))throw Error('Alternativa ausente em '+String(n+1));out.push({id:`ACE-GEN-${String(n+1).padStart(4,'0')}`,disciplina:disc,assunto,enunciado:C[v%C.length]+`Variação ${v+1}: `+enunciado,alternativas:ordered,gabarito:g,explicacao:`A alternativa ${g} está correta: ${cor}`,dificuldade:['facil','media','dificil'][n%3],fonte:'ACS - AE.pdf — expansão de treino'});}window.ACE_EXTRA_QUESTOES=out;})();