/* Nós Passa — proteção dos ambientes pagos por curso/cargo. */
(function(){
const script=document.currentScript,slug=script?.dataset?.course;
const U='https://ztqtcbzjesrkuaijmylm.supabase.co',K='sb_publishable_Lh0A_Ykm2h66ur3LojJKTQ_JdUVMK9d';
const IDS={'ace-marica':1,'transpetro':2,'inspetor-eletrica':3};
const id=IDS[slug];
const page=(title,text)=>{document.body.innerHTML='<div style="min-height:100vh;display:grid;place-items:center;background:#0d1014;color:#fff;font-family:Arial;padding:24px;text-align:center"><div style="max-width:620px"><div style="font-size:42px">⚠️</div><h2>'+title+'</h2><p style="color:#a6adb7;line-height:1.6">'+text+'</p><a href="minha-conta.html" style="display:inline-block;margin-top:12px;padding:11px 16px;border-radius:10px;background:#e4c64a;color:#111;font-weight:800;text-decoration:none">Voltar para minha conta</a></div></div>'};
const loading=()=>{document.body.innerHTML='<div id="np-loading" style="min-height:100vh;display:grid;place-items:center;background:#070a0e;color:#fff;font-family:Arial;padding:24px;text-align:center"><div><div style="width:42px;height:42px;border:3px solid #29313b;border-top-color:#e4c64a;border-radius:50%;margin:0 auto 18px;animation:spin .8s linear infinite"></div><h2>Abrindo sua plataforma…</h2><p style="color:#9da8b5">Validando sua conta e preparando o ambiente de estudos.</p></div></div><style>@keyframes spin{to{transform:rotate(360deg)}}</style>'};
const timeout=(ms)=>new Promise((_,reject)=>setTimeout(()=>reject(new Error('timeout')),ms));
const race=(p,ms)=>Promise.race([p,timeout(ms)]);
const stored=()=>{try{const key='sb-'+new URL(U).hostname.split('.')[0]+'-auth-token';const v=JSON.parse(localStorage.getItem(key)||'null'),s=v?.currentSession||v;if(s?.access_token&&s?.user)return s}catch(e){}return null};
const api=async(path,token,opts={})=>{const r=await race(fetch(U+path,{...opts,headers:{apikey:K,Authorization:'Bearer '+token,'Content-Type':'application/json',...(opts.headers||{})}}),12000);let data=null;try{data=await r.json()}catch(e){}if(!r.ok)throw new Error(data?.message||data?.error_description||data?.error||('HTTP '+r.status));return data};
if(!id){page('Curso não configurado.','Identificador do curso inválido.');return}loading();
(async()=>{try{let auth=stored();if(!auth){const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.js';s.async=true;document.head.appendChild(s);await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(new Error('timeout')),7000);s.onload=()=>{clearTimeout(t);resolve()};s.onerror=()=>{clearTimeout(t);reject(new Error('falha'))}});if(window.supabase?.createClient){const sb=window.supabase.createClient(U,K,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:false}});auth=(await race(sb.auth.getSession(),7000)).data?.session||null}}if(!auth?.access_token||!auth?.user){sessionStorage.setItem('ap_target',location.href);location.replace('login.html');return}const token=auth.access_token,user=auth.user;const rows=await api('/rest/v1/user_courses?select=status%2Cexpires_at&user_id=eq.'+encodeURIComponent(user.id)+'&course_id=eq.'+id+'&limit=1',token);const allowed=Array.isArray(rows)&&rows[0]?.status==='active'&&(!rows[0].expires_at||new Date(rows[0].expires_at)>new Date());if(!allowed){location.replace('minha-conta.html');return}window.__NP_AUTH_USER=user;const s=document.createElement('script');s.src='./study-dashboard-stable-v2.js?v=20260909-3';document.body.appendChild(s);s.onerror=()=>page('Não foi possível abrir a área de estudos.','O painel não carregou. Tente atualizar a página novamente.')
}catch(e){console.error('course-access',e);page('Não foi possível abrir sua plataforma.',e.message==='timeout'?'O serviço demorou para responder. Tente novamente.':'Erro: '+(e.message||'não foi possível validar o acesso.'))}})();
})();