/* Nós Passa — Meu Plano de Estudos (MVP)
 * Isolado do motor do dashboard. Usa Supabase para persistência por usuário/curso.
 */
(function(){
'use strict';
const SUPABASE_URL='https://ztqtcbzjesrkuaijmylm.supabase.co';
const SUPABASE_KEY='sb_publishable_Lh0A_Ykm2h66ur3LojJKTQ_JdUVMK9d';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{autoRefreshToken:true,persistSession:true,detectSessionInUrl:false}});
const qs=new URLSearchParams(location.search),courseSlug=qs.get('course');
const DAYS=['DOM','SEG','TER','QUA','QUI','SEX','SAB'];
const DAY_NAMES=['Domingo','Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado'];
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const pad=n=>String(Math.max(0,Math.floor(n))).padStart(2,'0');
let user=null,course=null,plan=null,activities=[],content=null,selectedDay=new Date().getDay(),editingId=null;
let timer={session:null,interval:null,intervalId:null,running:false,base:0,lastHeartbeat:0,tick:null};

function localDateStart(d=new Date()){const x=new Date(d);x.setHours(0,0,0,0);return x}
function localDateEnd(d=new Date()){const x=localDateStart(d);x.setDate(x.getDate()+1);return x}
function weekStart(d=new Date()){const x=localDateStart(d);x.setDate(x.getDate()-x.getDay());return x}
function iso(d){return d.toISOString()}
function fmtSecs(s){s=Math.max(0,Math.round(s));return `${pad(s/3600)}:${pad((s%3600)/60)}:${pad(s%60)}`}
function fmtShort(s){s=Math.max(0,Math.round(s));const h=Math.floor(s/3600),m=Math.floor((s%3600)/60);return h?`${h}h ${pad(m)}min`:`${m}min`}
function showNotice(text,type=''){const el=$('notice');if(!el)return;el.className='notice'+(type?' '+type:'');el.textContent=text;el.hidden=!text}
async function loadUser(){const{data:{user:u},error}=await sb.auth.getUser();if(error||!u){location.replace('login.html');return null}user=u;return u}
async function loadCourse(){if(!courseSlug)throw new Error('Curso não informado.');
  const{data,error}=await sb.from('user_courses').select('course_id,courses!inner(id,name,slug,active)').eq('user_id',user.id).eq('status','active').eq('courses.slug',courseSlug).maybeSingle();
  if(error||!data||!data.courses||data.courses.active===false)throw new Error('Você não possui acesso ativo a este curso.');
  if(data.courses.active===false)throw new Error('Este curso está indisponível.');
  if(data.course_id==null)throw new Error('Curso inválido.');
  course={id:Number(data.course_id),name:data.courses.name,slug:data.courses.slug};
}
async function loadPlan(){const{data,error}=await sb.from('study_plans').select('*').eq('user_id',user.id).eq('course_id',course.id).eq('active',true).maybeSingle();if(error)throw error;plan=data||null}
function renderShell(){
 document.title='Nós Passa — Meu Plano';
 $('courseName').textContent=course.name;
 $('userEmail').textContent=user.email||'Conta';
 $('back').href=`${courseDashboard()}`;
}
function courseDashboard(){return courseSlug==='ace-marica'?'ace_marica_app_fixed.html':courseSlug==='transpetro'?'transpetro.html':courseSlug==='inspetor-eletrica'?'inspetor_eletrica.html':'minha-conta.html'}
async function createPlan(){const name=($('planNameInput').value||'').trim()||'Meu Plano';const{data,error}=await sb.from('study_plans').insert({user_id:user.id,course_id:course.id,name,active:true}).select('*').single();if(error){if(error.code==='23505'){await loadPlan();return}throw error}plan=data;renderPlanMeta();render();}
function renderPlanMeta(){ $('planName').textContent=plan?.name||'Meu Plano';$('createWrap').hidden=!!plan }
function dayActivities(day){return activities.filter(a=>a.day_of_week===day&&a.active).sort((a,b)=>a.order_index-b.order_index||a.start_time.localeCompare(b.start_time))}
function renderDays(){const today=new Date().getDay();$('dayTabs').innerHTML=DAYS.map((d,i)=>`<button class="day-tab ${selectedDay===i?'active ':''}${today===i?'today':''}" data-day="${i}"><strong>${d}</strong><span>${String(weekDate(i).getDate()).padStart(2,'0')}/${String(weekDate(i).getMonth()+1).padStart(2,'0')}</span></button>`).join('');$('dayTabs').querySelectorAll('.day-tab').forEach(b=>b.onclick=()=>{selectedDay=Number(b.dataset.day);render()})}
function weekDate(i){const d=localDateStart();d.setDate(d.getDate()-d.getDay()+i);return d}
function renderTodaySummary(){const day=dayActivities(new Date().getDay()),planned=day.reduce((s,a)=>s+a.planned_duration,0);$('todayPlanned').textContent=fmtShort(planned*60);}
async function calculateStats(){const ds=localDateStart(),de=localDateEnd(),ws=weekStart(),we=new Date(ws);we.setDate(we.getDate()+7);const plannedToday=dayActivities(new Date().getDay()).reduce((s,a)=>s+a.planned_duration,0)*60;const plannedWeek=activities.filter(a=>a.active).reduce((s,a)=>s+a.planned_duration,0)*60;
 const{data:ints,error}=await sb.from('study_session_intervals').select('session_id,started_at,ended_at,last_heartbeat_at').eq('user_id',user.id).eq('course_id',course.id).lt('started_at',iso(we)).or(`ended_at.is.null,ended_at.gt.${iso(ws)}`);if(error)throw error;
 const calc=(start,end)=>Math.round((ints||[]).reduce((sum,i)=>{const a=Math.max(new Date(i.started_at).getTime(),start.getTime());const rawEnd=i.ended_at?new Date(i.ended_at):new Date(i.last_heartbeat_at||Date.now());const b=Math.min(rawEnd.getTime(),end.getTime());return sum+(b>a?(b-a)/1000:0)},0));
 const studiedToday=calc(ds,de),studiedWeek=calc(ws,we);
 const{data:sessions,error:se}=await sb.from('study_sessions').select('id,plan_activity_id,status,started_at,finished_at').eq('user_id',user.id).eq('course_id',course.id).gte('started_at',iso(ds)).lt('started_at',iso(de));if(se)throw se;
 const todayIds=new Set(day.map(a=>a.id));const doneIds=new Set((sessions||[]).filter(s=>todayIds.has(s.plan_activity_id)&&s.status==='completed').map(s=>s.plan_activity_id));
 $('todayPlanned').textContent=fmtShort(plannedToday);$('todayStudied').textContent=fmtShort(studiedToday);$('todayDone').textContent=`${doneIds.size}/${day.length}`;$('todayPending').textContent=Math.max(0,day.length-doneIds.size);$('todayProgress').style.width=`${plannedToday?Math.min(100,Math.round(studiedToday/plannedToday*100)):0}%`;
 $('weekPlanned').textContent=fmtShort(plannedWeek);$('weekStudied').textContent=fmtShort(studiedWeek);$('weekDone').textContent=String((sessions||[]).filter(s=>s.status==='completed').length);$('weekProgress').style.width=`${plannedWeek?Math.min(100,Math.round(studiedWeek/plannedWeek*100)):0}%`;
 return {sessions:sessions||[]};
}
function renderActivities(sessions=[]){const list=dayActivities(selectedDay),done=new Set(sessions.filter(s=>s.status==='completed').map(s=>s.plan_activity_id));$('dayTitle').textContent=DAY_NAMES[selectedDay];$('activityList').innerHTML=list.length?list.map((a,i)=>`<article class="activity ${done.has(a.id)?'done':''}"><div class="drag">☷</div><div class="activity-main"><div class="activity-time">${a.start_time.slice(0,5)} · ${a.planned_duration} min</div><div class="activity-title">${esc(a.subject)}</div><div class="activity-topic">${esc(a.topic)}</div></div><div class="activity-actions"><span class="badge ${done.has(a.id)?'ok':''}">${done.has(a.id)?'✓ Concluída':'Pendente'}</span><button class="icon-btn" title="Subir" onclick="window.moveActivity('${a.id}',-1)">↑</button><button class="icon-btn" title="Descer" onclick="window.moveActivity('${a.id}',1)">↓</button><button class="icon-btn" title="Editar" onclick="window.editActivity('${a.id}')">✎</button><button class="icon-btn" title="Excluir" onclick="window.deleteActivity('${a.id}')">×</button><button class="icon-btn start" onclick="window.startActivity('${a.id}')">▶ Iniciar</button></div></article>`).join(''):'<div class="empty">Nenhuma atividade cadastrada neste dia.<br><br>Adicione sua primeira sessão.</div>'}
async function render(){renderPlanMeta();renderDays();renderTodaySummary();const{sessions}=await calculateStats();renderActivities(sessions);await checkOpenSession()}
function openModal(activity){editingId=activity?.id||null;$('modalTitle').textContent=editingId?'Editar atividade':'Nova atividade';$('activityDay').value=activity?.day_of_week??selectedDay;$('activityTime').value=activity?.start_time?.slice(0,5)||'08:00';$('activitySubject').innerHTML=(content?.subjects||[]).map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('');if(activity){$('activitySubject').value=activity.subject;populateTopics(activity.subject);$('activityTopic').value=activity.topic;$('activityDuration').value=activity.planned_duration}else{$('activityTopic').innerHTML='<option value="">Selecione uma disciplina</option>';$('activityDuration').value=30;populateTopics($('activitySubject').value)}$('activityModal').classList.add('open')}
function closeModal(){$('activityModal').classList.remove('open');editingId=null}
function populateTopics(subject){const topics=content?.topics?.[subject]||[];$('activityTopic').innerHTML='<option value="">Selecione o assunto</option>'+topics.map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('')}
async function saveActivity(e){e.preventDefault();if(!plan)return showNotice('Crie seu plano antes de adicionar atividades.','error');const day=Number($('activityDay').value),time=$('activityTime').value,subject=$('activitySubject').value,topic=$('activityTopic').value,duration=Number($('activityDuration').value);if(!subject||!topic)return showNotice('Selecione a disciplina e o assunto.','error');if(!/^[0-9]{2}:[0-9]{2}$/.test(time))return showNotice('Informe um horário válido.','error');const payload={plan_id:plan.id,user_id:user.id,course_id:course.id,day_of_week:day,start_time:time,subject,topic,planned_duration:duration,active:true};let r;if(editingId){r=await sb.from('study_plan_activities').update(payload).eq('id',editingId).eq('user_id',user.id)}else{const order=dayActivities(day).length;r=await sb.from('study_plan_activities').insert({...payload,order_index:order})}if(r.error){showNotice(r.error.message||'Não foi possível salvar.','error');return}closeModal();showNotice('Atividade salva.','ok');await loadData();}
async function deleteActivity(id){if(!confirm('Excluir esta atividade do seu plano?'))return;const{error}=await sb.from('study_plan_activities').update({active:false}).eq('id',id).eq('user_id',user.id).eq('course_id',course.id);if(error)return showNotice(error.message,'error');await loadData()}
async function moveActivity(id,dir){const a=activities.find(x=>x.id===id);if(!a)return;const day=dayActivities(a.day_of_week);const idx=day.findIndex(x=>x.id===id),ni=idx+dir;if(ni<0||ni>=day.length)return;const reordered=[...day];[reordered[idx],reordered[ni]]=[reordered[ni],reordered[idx]];const{error}=await sb.rpc('reorder_study_plan_day',{p_plan_id:plan.id,p_course_id:course.id,p_day_of_week:a.day_of_week,p_activity_ids:reordered.map(x=>x.id)});if(error)return showNotice('Não foi possível reorganizar. '+error.message,'error');await loadData()}
function editActivity(id){const a=activities.find(x=>x.id===id);if(a)openModal(a)}
async function loadActivities(){const{data,error}=await sb.from('study_plan_activities').select('*').eq('user_id',user.id).eq('course_id',course.id).eq('plan_id',plan?.id||'00000000-0000-0000-0000-000000000000').eq('active',true).order('day_of_week').order('order_index').order('start_time');if(error)throw error;activities=data||[]}
async function loadData(){await loadPlan();if(plan)await loadActivities();else activities=[];await render()}
async function checkOpenSession(){const{data,error}=await sb.from('study_sessions').select('id,plan_activity_id,status,planned_duration,started_at,finished_at,actual_duration_seconds,created_at').eq('user_id',user.id).eq('course_id',course.id).in('status',['running','paused']).maybeSingle();if(error)throw error;if(!data){$('openSession').hidden=true;return null}const a=activities.find(x=>x.id===data.plan_activity_id);if(data.status==='running'){const{data:intv}=await sb.from('study_session_intervals').select('id,started_at,last_heartbeat_at,ended_at').eq('user_id',user.id).eq('course_id',course.id).eq('session_id',data.id).is('ended_at',null).maybeSingle();if(intv){const stale=Date.now()-new Date(intv.last_heartbeat_at||intv.started_at).getTime()>35000;if(stale){await sb.from('study_session_intervals').update({ended_at:intv.last_heartbeat_at,last_heartbeat_at:intv.last_heartbeat_at}).eq('id',intv.id);await sb.from('study_sessions').update({status:'paused'}).eq('id',data.id).eq('user_id',user.id);data.status='paused'}}}
 $('openSession').hidden=false;$('openSessionTitle').textContent=a?`${a.subject} — ${a.topic}`:'Sessão em andamento';$('openSessionText').textContent=data.status==='paused'?'A sessão está pausada e foi preservada.':'Existe uma sessão em andamento.';$('continueOpen').onclick=()=>resumeExisting(data.id);$('finishOpen').onclick=()=>finishExisting(data.id);return data}
async function recoverBeforeResume(sessionId){const{data:intv}=await sb.from('study_session_intervals').select('*').eq('session_id',sessionId).eq('user_id',user.id).eq('course_id',course.id).is('ended_at',null).maybeSingle();if(intv){await sb.from('study_session_intervals').update({ended_at:intv.last_heartbeat_at,last_heartbeat_at:intv.last_heartbeat_at}).eq('id',intv.id)}await sb.from('study_sessions').update({status:'paused'}).eq('id',sessionId).eq('user_id',user.id);}
async function resumeExisting(id){await recoverBeforeResume(id);const{error}=await startInterval(id);if(error)return showNotice(error.message,'error');await openTimer(id)}
async function finishExisting(id){if(!confirm('Encerrar esta sessão? O tempo já estudado será preservado.'))return;await recoverBeforeResume(id);await finishSession(id,false)}
async function startActivity(id){if(!plan)return showNotice('Crie seu plano primeiro.','error');const a=activities.find(x=>x.id===id);if(!a)return;const open=await checkOpenSession();if(open&&open.id){return showNotice('Já existe uma sessão aberta neste curso. Continue ou encerre a sessão atual antes de iniciar outra.','error')}
 const{data,error}=await sb.from('study_sessions').insert({user_id:user.id,course_id:course.id,plan_activity_id:id,planned_duration:a.planned_duration,status:'running'}).select('*').single();if(error){showNotice(error.message,'error');return}
 const created=await startInterval(data.id);if(created.error){await sb.from('study_sessions').delete().eq('id',data.id).eq('user_id',user.id);showNotice(created.error.message,'error');return}openTimer(data.id)
}
async function startInterval(sessionId){const now=new Date().toISOString();const{data,error}=await sb.from('study_session_intervals').insert({session_id:sessionId,user_id:user.id,course_id:course.id,started_at:now,last_heartbeat_at:now}).select('*').single();if(error)return{error};const r=await sb.from('study_sessions').update({status:'running'}).eq('id',sessionId).eq('user_id',user.id).eq('course_id',course.id);return{data,error:r.error}}
async function openTimer(sessionId){const{data,error}=await sb.from('study_sessions').select('*').eq('id',sessionId).eq('user_id',user.id).eq('course_id',course.id).single();if(error)throw error;timer.session=data;timer.running=data.status==='running';timer.base=Number(data.actual_duration_seconds||0);const{data:intv}=await sb.from('study_session_intervals').select('*').eq('session_id',sessionId).eq('user_id',user.id).eq('course_id',course.id).is('ended_at',null).maybeSingle();timer.interval=intv||null;timer.lastHeartbeat=intv?new Date(intv.last_heartbeat_at||intv.started_at).getTime():0;const a=activities.find(x=>x.id===data.plan_activity_id);$('timerTitle').textContent=a?`${a.subject}`:'Sessão';$('timerTopic').textContent=a?`${a.topic}`:'';$('timerPlanned').textContent=`Planejado: ${data.planned_duration} min`;$('timerSheet').classList.add('open');$('pauseBtn').hidden=!timer.running;$('resumeBtn').hidden=timer.running||!timer.interval;$('finishBtn').onclick=()=>window.finishCurrent();startTimerLoop()}
function currentDisplayed(){let s=timer.base;if(timer.running&&timer.interval){s+=(Date.now()-timer.lastHeartbeat)/1000}s=Math.max(0,s);return s}
function startTimerLoop(){clearInterval(timer.tick);const tick=()=>{$('timerTime').textContent=fmtSecs(currentDisplayed());};timer.tick=setInterval(tick,1000);tick();clearInterval(timer.heartbeat);timer.heartbeat=setInterval(()=>heartbeat(),15000)}
async function heartbeat(){if(!timer.session||!timer.running||!timer.interval)return;const now=new Date().toISOString();const{error}=await sb.from('study_session_intervals').update({last_heartbeat_at:now}).eq('id',timer.interval.id).eq('user_id',user.id);if(!error)timer.lastHeartbeat=Date.now();}
async function pauseCurrent(){if(!timer.session||!timer.running||!timer.interval)return;const now=new Date().toISOString();const{error}=await sb.from('study_session_intervals').update({ended_at:now,last_heartbeat_at:now}).eq('id',timer.interval.id).eq('user_id',user.id);if(error)return showNotice(error.message,'error');await sb.from('study_sessions').update({status:'paused'}).eq('id',timer.session.id).eq('user_id',user.id);timer.running=false;timer.interval=null;timer.base=currentDisplayed();$('pauseBtn').hidden=true;$('resumeBtn').hidden=false;await loadData()}
async function resumeCurrent(){if(!timer.session)return;const{data:intv,error}=await startInterval(timer.session.id);if(error)return showNotice(error.message,'error');timer.running=true;timer.interval=intv;timer.base=timer.session.actual_duration_seconds||0;timer.lastHeartbeat=Date.now();$('pauseBtn').hidden=false;$('resumeBtn').hidden=true;startTimerLoop()}
async function finishCurrent(){if(!timer.session)return;if(!confirm('Deseja concluir esta sessão?'))return;await finishSession(timer.session.id,true)}
async function finishSession(id,fromOpen=true){const{data:intv}=await sb.from('study_session_intervals').select('*').eq('session_id',id).eq('user_id',user.id).eq('course_id',course.id).is('ended_at',null).maybeSingle();if(intv){const now=new Date().toISOString();const{error}=await sb.from('study_session_intervals').update({ended_at:now,last_heartbeat_at:now}).eq('id',intv.id).eq('user_id',user.id);if(error)return showNotice(error.message,'error')}
 const{data:session,error:se}=await sb.from('study_sessions').select('actual_duration_seconds').eq('id',id).eq('user_id',user.id).single();if(se)throw se;const{error}=await sb.from('study_sessions').update({status:'completed',finished_at:new Date().toISOString()}).eq('id',id).eq('user_id',user.id).eq('course_id',course.id);if(error)return showNotice(error.message,'error');clearInterval(timer.tick);clearInterval(timer.heartbeat);timer={session:null,interval:null,intervalId:null,running:false,base:0,lastHeartbeat:0,tick:null};$('timerSheet').classList.remove('open');showNotice(`Sessão concluída: ${fmtShort(session.actual_duration_seconds||0)} estudados.`,'ok');await loadData()}
async function bootContent(){content=await window.NPStudyContent.load(courseSlug);$('activitySubject').innerHTML=(content.subjects||[]).map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('');$('activitySubject').onchange=()=>populateTopics($('activitySubject').value)}
async function init(){try{await loadUser();await loadCourse();renderShell();await bootContent();await loadPlan();if(!plan){$('createWrap').hidden=false;render();}else{await loadActivities();render()}$('createBtn').onclick=createPlan;$('newActivity').onclick=()=>openModal(null);$('closeModal').onclick=closeModal;$('cancelModal').onclick=closeModal;$('activityForm').onsubmit=saveActivity;$('pauseBtn').onclick=pauseCurrent;$('resumeBtn').onclick=resumeCurrent;window.addEventListener('beforeunload',()=>{if(timer.running)navigator.sendBeacon?.(SUPABASE_URL+'/rest/v1/study_session_intervals?id=eq.'+encodeURIComponent(timer.interval?.id||''),new Blob([JSON.stringify({last_heartbeat_at:new Date().toISOString()})],{type:'application/json'}))});}catch(e){console.error(e);showNotice(e.message||'Não foi possível carregar seu plano.','error')}}
window.moveActivity=moveActivity;window.editActivity=editActivity;window.deleteActivity=deleteActivity;window.startActivity=startActivity;window.finishCurrent=finishCurrent;
init();
})();
