(() => {'use strict';
const sb=supabase.createClient('https://ztqtcbzjesrkuaijmylm.supabase.co','sb_publishable_Lh0A_Ykm2h66ur3LojJKTQ_JdUVMK9d');
const $=id=>document.getElementById(id),msg=(v,bad=false)=>{let el=$('message');el.textContent=v;el.classList.toggle('error',bad)},tz='America/Sao_Paulo';let user=null,admin=false,mode='login',matches=[],picks=[];
const el=(tag,text,cls)=>{let x=document.createElement(tag);x.textContent=text;if(cls)x.className=cls;return x};
const date=x=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'medium',timeStyle:'short',timeZone:tz}).format(new Date(x));
const day=x=>new Intl.DateTimeFormat('en-CA',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:tz}).format(new Date(x));
function view(name){for(const n of ['games','mine','manage']){$(`${n}-view`).classList.toggle('hidden',n!==name);document.querySelector(`[data-view="${n}"]`)?.classList.toggle('active',n===name)}}
function setMode(x){mode=x;$('password-field').classList.toggle('hidden',x==='reset');$('email').required=x!=='recovery';$('email').closest('label').classList.toggle('hidden',x==='recovery');$('password').required=x!=='reset';$('auth-submit').textContent=({login:'Entrar',signup:'Criar conta',reset:'Enviar link de recuperação',recovery:'Salvar nova senha'})[x];msg('')}
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));setMode('login');
$('auth-form').onsubmit=async e=>{e.preventDefault();let email=$('email').value.trim(),password=$('password').value,r;if(mode==='recovery')r=await sb.auth.updateUser({password});else if(mode==='login')r=await sb.auth.signInWithPassword({email,password});else if(mode==='signup')r=await sb.auth.signUp({email,password,options:{emailRedirectTo:location.origin+'/palpites.html'}});else r=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/palpites.html'});if(r.error)return msg(r.error.message,true);if(mode==='recovery'){msg('Senha atualizada.');setMode('login')}else if(mode==='signup'&&!r.data.session)msg('Confira seu e-mail para confirmar a conta.');else if(mode==='reset')msg('Se esse e-mail estiver cadastrado, você receberá um link de recuperação.');else await boot()};
$('logout').onclick=async()=>{await sb.auth.signOut();user=null;location.reload()};
async function boot(){const r=await sb.auth.getUser();user=r.data.user;if(!user){$('auth').classList.remove('hidden');$('account').classList.add('hidden');return}const a=await sb.rpc('is_admin');admin=!a.error&&a.data===true;$('auth').classList.add('hidden');$('account').classList.remove('hidden');$('admin-nav').classList.toggle('hidden',!admin);$('traffic').classList.toggle('hidden',!admin);await refresh()}
async function refresh(){let [m,p]=await Promise.all([sb.from('np_matches').select('*').order('kickoff',{ascending:true}),sb.from('np_picks').select('match_id,choice,created_at').eq('user_id',user.id)]);if(m.error)return msg('Não foi possível carregar os jogos: '+m.error.message,true);if(p.error)return msg('Não foi possível carregar seus palpites: '+p.error.message,true);matches=m.data||[];picks=p.data||[];render();msg('')}
function render(){let list=$('game-list');list.replaceChildren();let published=matches.filter(m=>m.published);$('games-status').textContent=published.length?`${published.length} partida(s) disponível(is).`:'Ainda não há jogos publicados.';for(const m of published){let box=el('article','', 'game');box.append(el('div',m.competition,'muted'),el('strong',`${m.home_team} × ${m.away_team}`),el('p',`Início: ${date(m.kickoff)} · palpites até ${date(m.closes_at)}`,'muted'));let existing=picks.find(p=>p.match_id===m.id),closed=m.status!=='open'||Date.now()>=Date.parse(m.closes_at);if(m.home_odds&&m.draw_odds&&m.away_odds)box.append(el('p',`Cotações ilustrativas: ${m.home_team} ${m.home_odds} · Empate ${m.draw_odds} · ${m.away_team} ${m.away_odds}`,'muted'));box.append(el('p',existing?`Seu palpite: ${label(m,existing.choice)}`:closed?'Palpites encerrados.':'Escolha um resultado (sem valores ou pagamento).','badge'));if(!existing&&!closed){let row=el('div','', 'row');for(const [key,title] of [['home',m.home_team],['draw','Empate'],['away',m.away_team]]){let b=el('button',title);b.onclick=()=>pick(m.id,key);row.append(b)}box.append(row)}list.append(box)}let mine=$('my-list');mine.replaceChildren();for(const p of picks){let m=matches.find(x=>x.id===p.match_id);if(m)mine.append(el('p',`${m.home_team} × ${m.away_team}: ${label(m,p.choice)} · ${date(p.created_at)}`))}if(!picks.length)mine.append(el('p','Nenhum palpite registrado.','muted'));if(admin)renderAdmin()}
function label(m,choice){return choice==='home'?m.home_team:choice==='away'?m.away_team:'Empate'}
async function pick(id,choice){const r=await sb.from('np_picks').insert({match_id:id,user_id:user.id,choice});if(r.error)return msg(r.error.message,true);await refresh();msg('Palpite registrado. Não é uma aposta com dinheiro.')}
function renderAdmin(){let root=$('admin-games');root.replaceChildren();let count=new Map();for(const m of matches)count.set(day(m.kickoff),(count.get(day(m.kickoff))||0)+1);for(const m of matches){let box=el('article','', 'game');box.append(el('strong',`${m.home_team} × ${m.away_team}`),el('p',`${m.competition} · ${date(m.kickoff)} · fechamento ${date(m.closes_at)} · ${count.get(day(m.kickoff))}/4 no dia`,'muted'));let row=el('div','', 'row'),publish=el('button',m.published?'Retirar do site':'Publicar no site'),pause=el('button',m.status==='paused'?'Reabrir':'Travar palpites');publish.onclick=()=>update(m.id,{published:!m.published});pause.onclick=()=>update(m.id,{status:m.status==='paused'?'open':'paused'});row.append(publish,pause);box.append(row);let odds=el('div','', 'row');for(const [key,label] of [['home_odds','Casa'],['draw_odds','Empate'],['away_odds','Fora']]){let input=document.createElement('input');input.type='number';input.min='1.01';input.max='9999';input.step='0.01';input.placeholder=label;input.value=m[key]??'';input.dataset.odds=key;odds.append(input)}let save=el('button','Salvar cotações ilustrativas');save.onclick=async()=>{let data={};for(const input of odds.querySelectorAll('input')){let v=Number(input.value);if(!Number.isFinite(v)||v<=1)return msg('Preencha as três cotações acima de 1.',true);data[input.dataset.odds]=v}await update(m.id,data)};odds.append(save);box.append(odds);root.append(box)}if(!matches.length)root.append(el('p','Cadastre uma partida para começar.','muted'))}
async function update(id,fields){let r=await sb.from('np_matches').update(fields).eq('id',id);if(r.error)return msg(r.error.message,true);await refresh()}
$('match-form').onsubmit=async e=>{e.preventDefault();let kickoff=new Date($('kickoff').value),minutes=Number($('minutes').value);if(!Number.isFinite(kickoff.getTime())||kickoff<=new Date()||minutes<1||minutes>1440||kickoff.getTime()-minutes*60000<=Date.now())return msg('Informe jogo futuro e fechamento ainda não vencido.',true);let data={competition:$('competition').value.trim(),home_team:$('home').value.trim(),away_team:$('away').value.trim(),kickoff:kickoff.toISOString(),closes_at:new Date(kickoff.getTime()-minutes*60000).toISOString(),published:false};let r=await sb.from('np_matches').insert(data);if(r.error)return msg(r.error.message,true);$('match-form').reset();$('minutes').value=15;await refresh();view('manage');msg('Jogo cadastrado. Clique em Publicar no site quando estiver pronto.')};
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));
sb.auth.onAuthStateChange(event=>{if(event==='PASSWORD_RECOVERY'){setMode('recovery');$('auth').classList.remove('hidden');$('account').classList.add('hidden')}});boot();
})();
