
(function(){
const API='https://ztqtcbzjesrkuaijmylm.supabase.co/functions/v1/football-fixtures';
const lang=(document.documentElement.lang||'pt-BR').toLowerCase();
const tr=lang.startsWith('en')?{
 today:'Today',yesterday:'Yesterday',tomorrow:'Tomorrow',all:'All',live:'Live',finished:'Finished',scheduled:'Scheduled',games:'games',noGames:'No matches found for this date.',loading:'Loading matches...',error:'Could not load matches.',direct:'Football data automatically updated',comp:'Competitions'
}:lang.startsWith('es')?{
 today:'Hoy',yesterday:'Ayer',tomorrow:'Mañana',all:'Todos',live:'En vivo',finished:'Finalizados',scheduled:'Programados',games:'partidos',noGames:'No hay partidos para esta fecha.',loading:'Cargando partidos...',error:'No fue posible cargar los partidos.',direct:'Datos de fútbol actualizados automáticamente',comp:'Competiciones'
}:{
 today:'Hoje',yesterday:'Ontem',tomorrow:'Amanhã',all:'Todos',live:'Ao vivo',finished:'Encerrados',scheduled:'Programados',games:'jogos',noGames:'Nenhum jogo encontrado nesta data.',loading:'Carregando jogos...',error:'Não foi possível carregar os jogos.',direct:'Dados de futebol atualizados automaticamente',comp:'Competições'
};

const $=id=>document.getElementById(id);
const state={date:localISO(new Date()),filter:'all',data:null};

function localISO(d){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d),o=Object.fromEntries(p.map(x=>[x.type,x.value]));return o.year+'-'+o.month+'-'+o.day}
function addDays(iso,n){const [y,m,d]=iso.split('-').map(Number),x=new Date(Date.UTC(y,m-1,d+n,12));return x.toISOString().slice(0,10)}
function relLabel(iso){const today=localISO(new Date());if(iso===today)return tr.today;if(iso===addDays(today,-1))return tr.yesterday;if(iso===addDays(today,1))return tr.tomorrow;return new Intl.DateTimeFormat(lang,{weekday:'short',timeZone:'UTC'}).format(new Date(iso+'T12:00:00Z')).replace('.','')}
function dayNum(iso){return new Intl.DateTimeFormat(lang,{day:'2-digit',month:'2-digit',timeZone:'UTC'}).format(new Date(iso+'T12:00:00Z'))}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function statusType(s){const live=['1H','HT','2H','ET','BT','P','SUSP','INT','LIVE'];const fin=['FT','AET','PEN'];if(live.includes(s))return'live';if(fin.includes(s))return'finished';return'scheduled'}
function displayTime(f){const st=f.status?.short;if(statusType(st)==='live')return '<span class="live-dot"></span>'+esc((f.status.elapsed??'')+"'");if(statusType(st)==='finished')return esc(st);try{return new Intl.DateTimeFormat(lang,{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'America/Sao_Paulo'}).format(new Date(f.date))}catch{return'—'}}
function renderDates(){const box=$('datebar');let html='<button class="navday" data-shift="-1">‹</button>';for(let i=-2;i<=3;i++){const d=addDays(state.date,i);html+='<button class="day '+(i===0?'active':'')+'" data-date="'+d+'"><strong>'+esc(relLabel(d))+'</strong><span>'+esc(dayNum(d))+'</span></button>'}html+='<button class="navday" data-shift="1">›</button>';box.innerHTML=html;box.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{state.date=b.dataset.date;load()});box.querySelectorAll('[data-shift]').forEach(b=>b.onclick=()=>{state.date=addDays(state.date,Number(b.dataset.shift));load()})}
function filteredFixtures(){const a=state.data?.fixtures||[];if(state.filter==='all')return a;return a.filter(f=>statusType(f.status?.short)===state.filter)}
function group(fixtures){const m=new Map();fixtures.forEach(f=>{const k=(f.league?.country||'World')+'|'+(f.league?.id||0)+'|'+(f.league?.name||'Other');if(!m.has(k))m.set(k,{league:f.league,games:[]});m.get(k).games.push(f)});return [...m.values()].sort((a,b)=>(a.league.country||'').localeCompare(b.league.country||'')||(a.league.name||'').localeCompare(b.league.name||''))}
function renderSide(groups){$('side-title').textContent=tr.comp;$('side').innerHTML='<button class="side-btn active" data-league="all">'+tr.all+' <b>'+filteredFixtures().length+'</b></button>'+groups.map((g,i)=>'<button class="side-btn" data-league="'+i+'">'+esc(g.league.name)+' <b>'+g.games.length+'</b></button>').join('');$('side').querySelectorAll('[data-league]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.side-btn').forEach(x=>x.classList.remove('active'));btn.classList.add('active');if(btn.dataset.league==='all'){renderGames(groups)}else{renderGames([groups[Number(btn.dataset.league)]])}})
function gameHTML(f){const typ=statusType(f.status?.short),homeWin=f.teams?.home?.winner===true,awayWin=f.teams?.away?.winner===true;const score=(typ==='scheduled'||(f.goals?.home==null&&f.goals?.away==null))?'<span>–</span>':'<span>'+esc(f.goals?.home??0)+'</span><span>'+esc(f.goals?.away??0)+'</span>';return '<div class="game" data-id="'+esc(f.id)+'"><div class="time '+(typ==='live'?'live':'')+'">'+displayTime(f)+'</div><div class="teams"><div class="team '+(homeWin?'winner':'')+'"><img src="'+esc(f.teams.home.logo)+'" loading="lazy" alt=""><span>'+esc(f.teams.home.name)+'</span></div><div class="team '+(awayWin?'winner':'')+'"><img src="'+esc(f.teams.away.logo)+'" loading="lazy" alt=""><span>'+esc(f.teams.away.name)+'</span></div></div><div class="score">'+score+'<small>'+esc(f.status?.short||'')+'</small></div></div>'}
function renderGames(groups){const box=$('games');if(!groups.length){box.innerHTML='<div class="empty">'+tr.noGames+'</div>';return}box.innerHTML=groups.map(g=>'<section class="league"><div class="league-head">'+(g.league.flag?'<img src="'+esc(g.league.flag)+'" alt="">':'')+'<div><div class="country">'+esc(g.league.country||'World')+'</div><div class="name">'+esc(g.league.name)+'</div></div><div class="games-count">'+g.games.length+' '+tr.games+'</div></div>'+g.games.map(gameHTML).join('')+'</section>').join('')}
function rerender(){const fs=filteredFixtures();const groups=group(fs);$('count').textContent=fs.length+' '+tr.games;renderSide(groups);renderGames(groups)}
async function load(){renderDates();$('games').innerHTML='<div class="loading"><div class="spinner"></div>'+tr.loading+'</div>';$('count').textContent='';try{const r=await fetch(API+'?date='+encodeURIComponent(state.date));const d=await r.json();if(!r.ok||d.error)throw new Error(d.error||'HTTP '+r.status);state.data=d;rerender();$('source').innerHTML='<b>'+tr.direct+'</b> • '+esc(state.date)+(d.cached?' • cache':'')}catch(e){$('games').innerHTML='<div class="error">'+tr.error+'</div>';console.error(e)}}
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.filter=b.dataset.filter;rerender()});
$('filter-all').textContent=tr.all;$('filter-live').textContent=tr.live;$('filter-finished').textContent=tr.finished;$('filter-scheduled').textContent=tr.scheduled;
load();setInterval(()=>{if(state.date===localISO(new Date()))load()},300000);
})();
