(function(){
'use strict';
const CATALOG='https://ztqtcbzjesrkuaijmylm.supabase.co/functions/v1/football-catalog';
const lang=(document.documentElement.lang||'pt-BR').toLowerCase();
const tr=lang.startsWith('en')?{loading:'Loading team...',error:'Could not load this team.',summary:'Summary',results:'Results',calendar:'Calendar',next:'Next matches',recent:'Recent results',founded:'Founded',stadium:'Stadium',capacity:'Capacity',noNext:'No upcoming matches found.',noRecent:'No recent results available in the current data.',coverage:'Schedule and results are limited to dates currently saved on this site.'}:lang.startsWith('es')?{loading:'Cargando equipo...',error:'No fue posible cargar este equipo.',summary:'Resumen',results:'Resultados',calendar:'Calendario',next:'Próximos partidos',recent:'Resultados recientes',founded:'Fundado',stadium:'Estadio',capacity:'Capacidad',noNext:'No hay próximos partidos.',noRecent:'No hay resultados recientes en los datos disponibles.',coverage:'El calendario y los resultados se limitan a las fechas guardadas en este sitio.'}:{loading:'Carregando time...',error:'Não foi possível carregar este time.',summary:'Resumo',results:'Resultados',calendar:'Calendário',next:'Próximos jogos',recent:'Resultados recentes',founded:'Fundado',stadium:'Estádio',capacity:'Capacidade',noNext:'Nenhum próximo jogo encontrado.',noRecent:'Ainda não há resultados recentes deste time nos dados disponíveis.',coverage:'Calendário e resultados mostram apenas datas já salvas neste site.'};
const $=id=>document.getElementById(id),p=new URLSearchParams(location.search),id=Number(p.get('id')||0),teamName=(p.get('name')||'').trim();
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function statusType(s){return ['FT','AET','PEN'].includes(s)?'finished':['1H','HT','2H','ET','BT','P','LIVE'].includes(s)?'live':'scheduled'}
function fmtDate(f){try{return new Intl.DateTimeFormat(lang,{weekday:'short',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(f.date))}catch{return'—'}}
function teamUrl(t){const prefix=lang.startsWith('en')?'/en/':lang.startsWith('es')?'/es/':'/';const q=new URLSearchParams();if(t?.id)q.set('id',String(t.id));if(t?.name)q.set('name',t.name);return prefix+'team.html?'+q.toString()}
function matchUrl(f){return '/match.html?id='+encodeURIComponent(f.id)+'&date='+encodeURIComponent(String(f.date||'').slice(0,10))}
function fixture(f){const type=statusType(f.status?.short),score=type==='scheduled'?'<span>–</span>':'<span>'+esc(f.goals?.home??0)+'</span><span>'+esc(f.goals?.away??0)+'</span>';return '<div class="team-game"><div class="tg-date">'+esc(fmtDate(f))+'<small>'+esc(f.league?.name||'')+'</small></div><div class="tg-teams"><a href="'+teamUrl(f.teams.home)+'"><img src="'+esc(f.teams.home.logo||'')+'" alt=""><span>'+esc(f.teams.home.name)+'</span></a><a href="'+teamUrl(f.teams.away)+'"><img src="'+esc(f.teams.away.logo||'')+'" alt=""><span>'+esc(f.teams.away.name)+'</span></a></div><a class="tg-score" href="'+matchUrl(f)+'" aria-label="Detalhes da partida">'+score+'<small>'+esc(f.status?.short||'')+'</small></a></div>'}
function section(title,arr,empty){if(!arr?.length)return '<div class="team-section"><h2>'+title+'</h2><div class="team-empty">'+empty+'</div></div>';const groups=[],m=new Map();arr.forEach(f=>{const k=(f.league?.country||'World')+'|'+(f.league?.id||0);if(!m.has(k))m.set(k,{league:f.league,games:[]});m.get(k).games.push(f)});m.forEach(g=>groups.push(g));return '<div class="team-section"><h2>'+title+'</h2>'+groups.map(g=>'<div class="team-league"><div class="team-league-head">'+(g.league?.flag?'<img src="'+esc(g.league.flag)+'" alt="">':'')+'<b>'+esc(g.league?.country||'World')+' · '+esc(g.league?.name||'')+'</b></div>'+g.games.map(fixture).join('')+'</div>').join('')+'</div>'}
function setTab(tab){document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==tab)}
async function load(){if(!id&&!teamName){$('team-content').innerHTML='<div class="team-error">'+tr.error+'</div>';return}$('team-content').innerHTML='<div class="team-loading">'+tr.loading+'</div>';try{const params=new URLSearchParams({action:'team-summary'});if(id)params.set('id',String(id));if(teamName)params.set('name',teamName);const r=await fetch(CATALOG+'?'+params.toString());const d=await r.json();if(!r.ok||d.error||!d.team)throw new Error('load');const t=d.team;document.title=t.name+' — Nós Passa';$('team-content').innerHTML='<section class="team-hero"><div class="team-logo"><img src="'+esc(t.logo||'')+'" alt=""></div><div class="team-title"><span>'+esc(t.country||'')+'</span><h1>'+esc(t.name)+'</h1><div class="team-meta">'+(t.founded?'<span><b>'+tr.founded+':</b> '+esc(t.founded)+'</span>':'')+(t.venue?.name?'<span><b>'+tr.stadium+':</b> '+esc(t.venue.name)+'</span>':'')+(t.venue?.capacity?'<span><b>'+tr.capacity+':</b> '+Number(t.venue.capacity).toLocaleString(lang)+'</span>':'')+'</div></div></section><p class="team-coverage">'+tr.coverage+'</p><nav class="team-tabs"><button class="active" data-tab="summary">'+tr.summary+'</button><button data-tab="results">'+tr.results+'</button><button data-tab="calendar">'+tr.calendar+'</button></nav><div data-panel="summary">'+section(tr.next,(d.next||[]).slice(0,6),tr.noNext)+section(tr.recent,(d.recent||[]).slice(0,6),tr.noRecent)+'</div><div data-panel="results" hidden>'+section(tr.recent,d.recent||[],tr.noRecent)+'</div><div data-panel="calendar" hidden>'+section(tr.next,d.next||[],tr.noNext)+'</div>';document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab))}catch(e){$('team-content').innerHTML='<div class="team-error">'+tr.error+'</div>'}}
load();
})();