import { createClient } from 'npm:@supabase/supabase-js@2'
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}})
function parseSignature(v:string|null){const o:Record<string,string>={};for(const p of(v||'').split(',')){const [k,x]=p.split('=',2);if(k&&x)o[k.trim()]=x.trim()}return o}
function safe(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
async function hmac(secret:string,msg:string){const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const s=await crypto.subtle.sign('HMAC',k,new TextEncoder().encode(msg));return[...new Uint8Array(s)].map(b=>b.toString(16).padStart(2,'0')).join('')}
async function payment(token:string,id:string){for(const delay of[0,2000,4000,6000]){if(delay)await new Promise(r=>setTimeout(r,delay));const r=await fetch(`https://api.mercadopago.com/v1/payments/${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok||!d?.id)return{ok:false,data:d};if(!['pending','in_process','authorized'].includes(String(d.status)))return{ok:true,data:d}}return{ok:true,data:null}}
async function invoice(token:string,id:string){const r=await fetch(`https://api.mercadopago.com/authorized_payments/${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();return{ok:r.ok&&!!d?.id,data:d}}
Deno.serve(async req=>{
 if(req.method!=='POST')return json({message:'Método não permitido.'},405)
 const u=new URL(req.url),id=u.searchParams.get('data.id')||u.searchParams.get('data_id'),type=u.searchParams.get('type')||u.searchParams.get('topic')||'',rid=req.headers.get('x-request-id')||'',sig=parseSignature(req.headers.get('x-signature')),secret=Deno.env.get('MP_WEBHOOK_SECRET')
 if(!secret||!id||!sig.v1||!sig.ts)return json({message:'Webhook inválido.'},401)
 const parts=[`id:${id}`];if(rid)parts.push(`request-id:${rid}`);parts.push(`ts:${sig.ts}`);if(!safe(await hmac(secret,parts.join(';')+';'),sig.v1))return json({message:'Assinatura inválida.'},401)
 const token=Deno.env.get('MP_ACCESS_TOKEN'),url=Deno.env.get('SUPABASE_URL')!,key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'),site=Deno.env.get('SITE_URL');if(!token||!key||!site)return json({message:'Configuração do servidor incompleta.'},500);const db=createClient(url,key)
 if(type==='subscription_preapproval'){
   const r=await fetch(`https://api.mercadopago.com/preapproval/${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${token}`}}),s=await r.json();if(!r.ok||!s?.id)return json({message:'Assinatura não encontrada.'},404)
   const q=await db.from('purchases').select('id,metadata').or(`provider_subscription_id.eq.${s.id},metadata->>subscription_id.eq.${s.id}`).maybeSingle();if(!q.data)return json({received:true,linked:false})
   const metadata={...(q.data.metadata||{}),subscription_status:s.status||null,next_payment_date:s.next_payment_date||null,subscription_last_modified:s.last_modified||null};await db.from('purchases').update({next_billing_at:s.next_payment_date||null,metadata}).eq('id',q.data.id);return json({received:true,subscription:s.id,status:s.status})
 }
 if(type==='subscription_authorized_payment'){
   const r=await invoice(token,id);if(!r.ok)return json({message:'Fatura recorrente não encontrada.'},404);const inv=r.data,subId=String(inv.preapproval_id||'');if(!subId)return json({message:'Fatura sem preapproval_id.'},422)
   const base=await db.from('purchases').select('id,user_id,course_id,provider_subscription_id,metadata').eq('provider_subscription_id',subId).maybeSingle();if(!base.data)return json({received:true,linked:false})
   const paymentId=String(inv.payment?.id||'');if(!paymentId)return json({received:true,linked:true});const dup=await db.from('purchases').select('id').eq('provider_payment_id',paymentId).maybeSingle();if(dup.data)return json({received:true,duplicate:true})
   const ps=String(inv.payment?.status||inv.summarized||inv.status||'pending'),paid=ps==='approved'||ps==='accredited',failed=['rejected','cancelled','refunded','charged_back'].includes(ps),status=paid?'paid':failed?'failed':'pending',paidAt=paid?(inv.payment?.date_approved||new Date().toISOString()):null
   const ins=await db.from('purchases').insert({user_id:base.data.user_id,course_id:base.data.course_id,amount_cents:590,currency:'BRL',status,provider:'mercadopago',provider_payment_id:paymentId,payment_method:inv.payment?.payment_method_id||null,paid_at:paidAt,billing_mode:'recurring',provider_subscription_id:subId,next_billing_at:inv.debit_date||null,metadata:{payment_flow:'subscription_renewal',invoice_id:String(id),subscription_id:subId,mp_status:ps}}).select('id').single();if(ins.error)return json({message:'Falha ao registrar a renovação.'},500)
   // purchases_paid_grant_access extends access exactly once for this paid renewal.
   await db.from('purchases').update({metadata:{...(base.data.metadata||{}),last_recurring_payment_id:paymentId,last_recurring_status:ps}}).eq('id',base.data.id);return json({received:true,renewal_purchase_id:ins.data?.id,status})
 }
 const r=await payment(token,id);if(!r.ok||!r.data?.id)return json({message:'Pagamento não encontrado.'},404);const p=r.data,pid=p.external_reference;if(!pid)return json({message:'Pagamento sem external_reference.'},422)
 const q=await db.from('purchases').select('id,user_id,course_id,amount_cents,status,billing_mode,metadata,provider_subscription_id').eq('id',pid).single();if(q.error||!q.data)return json({message:'Compra interna não encontrada.'},404)
 if(Math.abs(Number(p.transaction_amount)-Number(q.data.amount_cents)/100)>.001)return json({message:'Valor do pagamento não confere.'},409)
 const old=q.data.metadata||{};if(String(old.last_payment_id||'')===String(p.id)&&String(old.mp_status||'')===String(p.status))return json({received:true,duplicate:true})
 const map:Record<string,string>={approved:'paid',rejected:'failed',cancelled:'cancelled',refunded:'refunded',charged_back:'refunded',in_process:'pending',pending:'pending',authorized:'pending'},status=map[String(p.status)]||'pending';const patch={status,provider:'mercadopago',provider_payment_id:String(p.id),payment_method:p.payment_method_id||null,paid_at:status==='paid'?(p.date_approved||new Date().toISOString()):null,metadata:{...old,last_payment_id:String(p.id),mp_status:p.status,status_detail:p.status_detail||null,payment_id:p.id,live_mode:p.live_mode??null}};const up=await db.from('purchases').update(patch).eq('id',q.data.id);if(up.error)return json({message:'Falha ao atualizar compra.'},500);if(status==='pending')return json({message:'Pagamento pendente.'},503)
 if(status==='paid'&&String(q.data.billing_mode||'')==='monthly'&&!q.data.provider_subscription_id&&!old.subscription_id){
   const paidAt=p.date_approved||new Date().toISOString(),start=new Date(new Date(paidAt).getTime()+30*24*60*60*1000),email=String(p.payer?.email||'');if(email){
     const r=await fetch('https://api.mercadopago.com/preapproval',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({reason:'Nós Passa — renovação mensal',external_reference:String(q.data.id),payer_email:email,auto_recurring:{frequency:1,frequency_type:'months',start_date:start.toISOString(),transaction_amount:5.90,currency_id:'BRL'},back_url:`${site.replace(/\/$/,'')}/pagamento.html?purchase=${q.data.id}`,status:'pending'})}),s=await r.json();if(r.ok&&s?.id){await db.from('purchases').update({provider_subscription_id:String(s.id),next_billing_at:start.toISOString(),metadata:{...old,subscription_id:String(s.id),subscription_status:s.status||'pending',subscription_init_point:s.init_point||null,first_month_price_cents:100,recurring_price_cents:590,recurring_start_at:start.toISOString()}}).eq('id',q.data.id)}else console.error('subscription creation error',r.status,s)
   }
 }
 return json({received:true})
})
