/* AprovaAI — Inspetor de Elétrica N1
 * Banco autoral construído a partir dos conteúdos públicos do PROMINP 2006–2008,
 * referências de provas de elétrica da Petrobras/Cesgranrio e ementas de formação
 * de Inspetor de Elétrica N1. Não reproduz textos de provas oficiais.
 */
(function(){
const Q=[]; const add=(id,disc,assunto,sub,en,alts,gabarito,exp,fonte='Autorais AprovaAI — estilo PROMINP/Cesgranrio')=>Q.push({id,disciplina:disc,assunto,subassunto:sub,dificuldade:'media',enunciado:en,alternativas:{A:alts[0],B:alts[1],C:alts[2],D:alts[3],E:alts[4]},gabarito,explicacao:exp,tipo:'inedita',fonte});
let n=1;
const q=(d,a,s,detail,en,alts,g,x,f)=>add('IE-'+String(n++).padStart(3,'0'),d,a,detail?(`${s} — ${detail}`):s,en,alts,g,x,f);
// ELETROTÉCNICA
q('Elétrica','Eletrotécnica','Lei de Ohm','Resistência','Uma carga resistiva de 20 ohms é alimentada por 120 V. A corrente é:', ['2 A','4 A','6 A','8 A','10 A'],'C','Pela Lei de Ohm, I=V/R=120/20=6 A.');
q('Elétrica','Eletrotécnica','Lei de Ohm','Potência','Um resistor de 10 ohms percorrido por 3 A dissipa:', ['9 W','30 W','60 W','90 W','300 W'],'D','P=R·I²=10·9=90 W.');
q('Elétrica','Eletrotécnica','Associação de resistores','Série','Dois resistores de 10 ohms e 20 ohms estão em série. A resistência equivalente é:', ['5 ohms','10 ohms','20 ohms','30 ohms','200 ohms'],'D','Em série, as resistências somam: 10+20=30 ohms.');
q('Elétrica','Eletrotécnica','Associação de resistores','Paralelo','Dois resistores de 10 ohms e 20 ohms em paralelo possuem resistência equivalente:', ['6,67 ohms','10 ohms','15 ohms','30 ohms','200 ohms'],'A','Req=(10·20)/(10+20)=200/30≈6,67 ohms.');
q('Elétrica','Eletrotécnica','Leis de Kirchhoff','KCL','Em um nó ideal de um circuito, a soma algébrica das correntes é igual a:', ['A zero','À tensão do circuito','À resistência equivalente','À potência ativa','Ao fator de potência'],'A','A Lei das Correntes de Kirchhoff estabelece soma algébrica das correntes no nó igual a zero.');
q('Elétrica','Eletrotécnica','CC e CA','Valor eficaz','Para uma tensão senoidal de 311 V de pico, o valor eficaz é aproximadamente:', ['110 V','155,5 V','220 V','311 V','440 V'],'C','Para senoide, Vrms=Vp/√2≈311/1,414≈220 V.');
q('Elétrica','Eletrotécnica','CA','Frequência','Uma fonte de 60 Hz completa quantos ciclos por segundo?', ['6','30','60','120','360'],'C','Hertz representa ciclos por segundo.');
q('Elétrica','Eletrotécnica','CA','Reatância indutiva','A reatância indutiva de uma bobina aumenta quando a frequência:', ['Diminui','Aumenta','Torna-se zero','Fica negativa','É independente da frequência'],'B','XL=2πfL; mantendo L, XL cresce com a frequência.');
q('Elétrica','Eletrotécnica','Potência em CA','Potência aparente','A unidade da potência aparente em circuitos CA é:', ['W','var','VA','J','Wh'],'C','Potência aparente é expressa em volt-ampère (VA).');
q('Elétrica','Eletrotécnica','Fator de potência','Correção','A correção do fator de potência de uma carga predominantemente indutiva é normalmente feita com:', ['Resistores em série','Capacitores em paralelo','Diodos em série','Fusíveis em paralelo','Transformadores sem carga'],'B','Capacitores fornecem potência reativa capacitiva, compensando parte da demanda indutiva.');
q('Elétrica','Eletrotécnica','Sistemas trifásicos','Tensão de linha','Em sistema trifásico equilibrado ligado em estrela, a tensão de linha é:', ['Igual à tensão de fase','√3 vezes a tensão de fase','3 vezes a tensão de fase','Metade da tensão de fase','Independente da tensão de fase'],'B','Em estrela equilibrada, VL=√3·VF.');
q('Elétrica','Eletrotécnica','Eletromagnetismo','Indução','A tensão induzida em uma bobina está relacionada à variação do:', ['Fluxo magnético','Peso do condutor','Comprimento da tomada','Fator de potência apenas','Diâmetro do disjuntor'],'A','A indução eletromagnética decorre da variação do fluxo magnético concatenado.');
q('Elétrica','Eletrotécnica','Corrente contínua','Energia','Uma carga de 100 W funcionando durante 5 h consome:', ['20 Wh','100 Wh','200 Wh','500 Wh','5 kWh'],'D','E=P·t=100 W·5 h=500 Wh=0,5 kWh.');
q('Elétrica','Eletrotécnica','Circuitos','Curto-circuito','Um curto-circuito caracteriza-se, em geral, por:', ['Impedância muito elevada','Corrente muito baixa','Caminho de baixa impedância e corrente elevada','Ausência de corrente','Aumento obrigatório da resistência de carga'],'C','O curto cria caminho de baixa impedância e pode produzir corrente muito elevada.');
q('Elétrica','Eletrotécnica','Materiais','Condutor','Entre cobre e borracha, o material normalmente utilizado como condutor elétrico é:', ['Borracha','Cobre','Vidro','Cerâmica','PVC'],'B','Cobre apresenta alta condutividade e é largamente usado em condutores.');
// MÁQUINAS E DISPOSITIVOS BT
q('Elétrica','Máquinas e dispositivos BT','Transformadores','Princípio','Um transformador ideal transfere energia elétrica entre enrolamentos por meio de:', ['Indução eletromagnética','Combustão','Atrito','Efeito piezoelétrico exclusivamente','Eletrólise'],'A','A transferência ocorre por indução eletromagnética entre os enrolamentos.');
q('Elétrica','Máquinas e dispositivos BT','Transformadores','Relação de transformação','Num transformador ideal, com 1000 espiras no primário e 100 espiras no secundário, a relação Vp/Vs é:', ['0,1','1','5','10','100'],'D','Para transformador ideal Vp/Vs=Np/Ns=1000/100=10.');
q('Elétrica','Máquinas e dispositivos BT','Motores','Indução','O motor de indução trifásico possui rotor que, em operação normal, gira:', ['Exatamente na velocidade síncrona','Com velocidade ligeiramente inferior à síncrona','Sempre acima da síncrona','Sem relação com o campo girante','Somente se houver escovas'],'B','O escorregamento necessário à indução de corrente no rotor faz a velocidade ser inferior à síncrona.');
q('Elétrica','Máquinas e dispositivos BT','Motores','Partida','A partida direta de um motor de indução tende a apresentar:', ['Corrente de partida elevada','Corrente de partida zero','Fator de potência unitário obrigatório','Tensão nula no motor','Potência sempre reduzida a zero'],'A','A partida direta conecta o motor diretamente à rede e normalmente produz alta corrente de partida.');
q('Elétrica','Máquinas e dispositivos BT','Acionamentos','Inversor de frequência','Um inversor de frequência é utilizado principalmente para:', ['Variar a frequência/tensão de alimentação do motor','Medir resistência de isolamento','Substituir todo aterramento','Aumentar a frequência da rede pública','Eliminar qualquer proteção'],'A','O inversor controla frequência e tensão aplicadas ao motor, permitindo controle de velocidade.');
q('Elétrica','Máquinas e dispositivos BT','Acionamentos','Soft starter','A função principal de uma soft starter é:', ['Reduzir esforços e corrente durante a partida','Medir resistência de terra','Elevar permanentemente a tensão da rede','Substituir o motor','Gerar energia ativa'],'A','A soft starter controla a tensão aplicada na partida, reduzindo corrente e esforços mecânicos.');
q('Elétrica','Máquinas e dispositivos BT','Proteção','Disjuntor','Um disjuntor termomagnético protege principalmente contra:', ['Sobrecarga e curto-circuito','Somente subtensão','Somente perda de fase','Somente harmônicas','Somente baixa resistência de isolamento'],'A','A proteção termomagnética atua tipicamente contra sobrecarga e curto-circuito.');
q('Elétrica','Máquinas e dispositivos BT','Proteção','DR','O dispositivo diferencial residual (DR) é destinado a detectar principalmente:', ['Corrente residual/fuga para terra','Temperatura ambiente','Frequência mecânica','Pressão hidráulica','Potência mecânica'],'A','O DR compara correntes e atua quando identifica desequilíbrio compatível com corrente residual.');
q('Elétrica','Máquinas e dispositivos BT','Proteção','Fusível','A característica essencial de um fusível é interromper o circuito quando:', ['A corrente ultrapassa seu limite por condição de atuação','A tensão se torna exatamente zero','A frequência cai para 50 Hz','O fator de potência vira capacitivo','A resistência do circuito aumenta'],'A','O elemento fusível aquece e se funde quando a corrente ultrapassa condições previstas de atuação.');
q('Elétrica','Máquinas e dispositivos BT','Comandos elétricos','Contator','Um contator é empregado principalmente para:', ['Manobra de cargas/circuitos de potência por comando elétrico','Medição de resistência de terra','Medição de vazão','Correção de fator de potência sozinho','Conversão CA-CC sem eletrônica'],'A','Contatores permitem manobra frequente de circuitos de potência a partir de um circuito de comando.');
q('Elétrica','Máquinas e dispositivos BT','Comandos elétricos','Relé térmico','O relé de sobrecarga usado com motores atua principalmente para proteger contra:', ['Sobrecarga prolongada','Curto instantâneo de altíssima corrente como função única','Descarga atmosférica','Baixa iluminação','Erro de leitura de planta'],'A','O relé térmico/eletrônico de sobrecarga protege o motor contra sobrecarga prolongada, conforme ajuste.');
// MEDIÇÕES
q('Elétrica','Medições elétricas','Multímetro','Tensão','Para medir tensão com um multímetro, o instrumento é ligado normalmente:', ['Em paralelo com o ponto de medição','Em série com a carga','No lugar do fusível','Somente ao terra','Sempre com o circuito desligado'],'A','Voltímetros possuem alta impedância e são conectados em paralelo ao elemento ou pontos cuja tensão se deseja medir.');
q('Elétrica','Medições elétricas','Multímetro','Corrente','Para medir corrente em um ramo do circuito, o amperímetro deve ser ligado:', ['Em paralelo','Em série','Em circuito aberto','Somente entre fase e terra','Ao infinito'],'B','A corrente do ramo deve atravessar o instrumento, por isso ele é inserido em série.');
q('Elétrica','Medições elétricas','Resistência','Ohmímetro','A medição de resistência com ohmímetro deve ser feita, como regra de segurança e método:', ['Com o circuito desenergizado','Sempre energizado','Somente em alta tensão','Em paralelo com outra fonte','Durante curto-circuito'],'A','Ohmímetros aplicam sua própria excitação; a medição deve ser feita em circuito desenergizado e adequadamente isolado.');
q('Elétrica','Medições elétricas','Isolação','Megômetro','O megômetro é utilizado principalmente para medir:', ['Resistência de isolamento','Fator de potência','Frequência da rede','Velocidade do motor','Corrente de curto-circuito de uma subestação'],'A','O megômetro aplica tensão de ensaio apropriada para avaliar a resistência do isolamento.');
q('Elétrica','Medições elétricas','Aterramento','Resistência de terra','O ensaio de resistência de aterramento busca avaliar principalmente:', ['A oposição oferecida pelo sistema de aterramento à passagem de corrente','A potência mecânica do motor','A tensão nominal do transformador','A rotação do eixo','A iluminação do ambiente'],'A','O valor medido caracteriza a resistência/impedância de dispersão do sistema de aterramento conforme o método empregado.');
q('Elétrica','Medições elétricas','Instrumentos','Rastreabilidade','Um instrumento de medição com calibração rastreável deve permitir:', ['Relacionar o resultado a padrões por uma cadeia documentada de calibrações','Alterar automaticamente a tensão da rede','Substituir o projeto','Operar sem identificação','Dispensar registros'],'A','Rastreabilidade metrológica relaciona o resultado a referências/padrões documentados por uma cadeia de calibração.');
q('Elétrica','Medições elétricas','Instrumentos','Categoria de medição','A categoria de medição de um instrumento elétrico está relacionada à:', ['Capacidade de suportar transientes e ao ambiente de medição previsto','Cor do instrumento','Marca do fabricante apenas','Dimensão da tela somente','Quantidade de teclas'],'A','As categorias de medição definem ambientes e níveis de transientes para os quais o equipamento é projetado.');
// DESENHOS
q('Elétrica','Desenho técnico','Esquemas','Diagrama unifilar','Em um diagrama unifilar, vários condutores de um sistema podem ser representados:', ['Por uma única linha simbólica com convenções','Sempre por uma fotografia','Somente por texto','Por uma linha obrigatoriamente real','Sem qualquer simbologia'],'A','O unifilar simplifica a representação usando uma linha para representar circuitos/conjuntos de condutores conforme simbologia.');
q('Elétrica','Desenho técnico','Símbolos','Leitura','A leitura correta de um esquema elétrico deve considerar principalmente:', ['Simbologia, identificação dos componentes e conexões','Somente cores','Somente escala gráfica','Somente tamanho da folha','Somente o título'],'A','A interpretação depende das convenções gráficas, referências dos componentes e relações elétricas mostradas.');
q('Elétrica','Desenho técnico','Projetos','Diagrama funcional','Um diagrama funcional enfatiza:', ['A lógica/funcionamento do circuito','A resistência mecânica do concreto','A localização geográfica apenas','A pintura dos equipamentos','A massa dos cabos'],'A','O diagrama funcional representa a lógica e a relação funcional entre elementos.');
q('Elétrica','Desenho técnico','Diagramas','Lista de cabos','Uma lista de cabos é útil para relacionar:', ['Identificação, origem, destino e características dos cabos','Somente nomes de operadores','Somente custos administrativos','Somente horas trabalhadas','Somente temperatura ambiente'],'A','A lista de cabos organiza dados de identificação e conexão necessários à instalação/inspeção.');
// INSPEÇÃO / QUALIDADE / METROLOGIA
q('Qualidade','Inspeção de qualidade','Inspeção','Conformidade','Em uma inspeção de recebimento, a comparação principal deve ser feita entre o equipamento recebido e:', ['Documentos técnicos, especificações e critérios de aceitação aplicáveis','A preferência pessoal do inspetor','A embalagem apenas','O preço pago','Uma fotografia aleatória'],'A','A inspeção deve confrontar características observadas com requisitos documentados e critérios aplicáveis.');
q('Qualidade','Inspeção de qualidade','Inspeção','Plano de inspeção','Um plano de inspeção normalmente define:', ['O que inspecionar, quando, como e com quais critérios/registros','Somente o salário dos inspetores','Somente o cronograma de férias','Somente a marca do instrumento','Somente o nome do cliente'],'A','O plano organiza pontos de inspeção, métodos, responsabilidades, critérios e evidências.');
q('Qualidade','ISO 9001','Sistema da qualidade','Evidência','Um registro de inspeção tem como função principal:', ['Demonstrar objetivamente o resultado verificado','Substituir o procedimento para sempre','Eliminar a necessidade de critérios','Servir somente como publicidade','Impedir rastreabilidade'],'A','Registros fornecem evidência objetiva de que uma atividade foi executada e de seus resultados.');
q('Qualidade','Metrologia','SI','Unidade de corrente','No SI, a unidade de corrente elétrica é:', ['Volt','Ampere','Ohm','Watt','Farad'],'B','A unidade SI da corrente elétrica é o ampere (A).');
q('Qualidade','Metrologia','Algarismos significativos','Arredondamento','Ao apresentar um resultado de medição, o arredondamento deve ser compatível com:', ['A resolução/incerteza e a regra de apresentação adotada','Qualquer número de casas escolhido ao acaso','Somente a cor do instrumento','O tamanho da peça','A idade do equipamento'],'A','O número de dígitos deve ser coerente com resolução, incerteza e regra de apresentação.');
q('Qualidade','Metrologia','Conversão','Comprimento','1 metro equivale a:', ['10 cm','100 cm','1000 cm','0,1 cm','10000 cm'],'B','O metro possui 100 centímetros.');
q('Qualidade','Metrologia','Escalas','Leitura de desenho','Se uma escala 1:100 é usada em uma planta, 1 cm no desenho representa:', ['1 mm real','10 cm reais','1 m real','10 m reais','100 m reais'],'C','Na escala 1:100, 1 cm no desenho corresponde a 100 cm, ou 1 m, no real.');
// SEGURANÇA / NR10
q('Segurança','Segurança elétrica','NR-10','Princípio','A NR-10 trata principalmente de:', ['Segurança em instalações e serviços em eletricidade','Inspeção de vasos de pressão','Trabalho rural','Proteção contra incêndio exclusivamente','Transporte de cargas'],'A','A NR-10 estabelece requisitos e condições mínimas para segurança em instalações e serviços em eletricidade.','NR-10 — referência normativa; conferir versão vigente no estudo final.');
q('Segurança','Segurança elétrica','Desenergização','Sequência','A desenergização segura deve incluir, entre outras medidas:', ['Seccionamento, impedimento de reenergização, constatação da ausência de tensão e medidas de proteção aplicáveis','Somente desligar a iluminação','Somente retirar um fusível','Apenas avisar verbalmente','Aumentar a tensão'],'A','A desenergização exige uma sequência controlada e verificação de ausência de tensão, além das medidas previstas para o trabalho.','NR-10 / procedimentos de segurança.');
q('Segurança','Segurança elétrica','EPI/EPC','Prioridade','Em segurança, proteção coletiva deve ser priorizada em relação à:', ['Proteção individual, quando tecnicamente aplicável','Sinalização','Documentação','Inspeção','Qualificação'],'A','A hierarquia de controles privilegia medidas coletivas quando aplicáveis, sem eliminar EPI quando necessário.');
q('Segurança','Segurança elétrica','Áreas classificadas','Equipamentos','Em área classificada, a seleção de equipamento elétrico deve considerar:', ['A classificação da área e os requisitos de certificação/proteção aplicáveis','Somente a potência nominal','Somente a cor','Somente o peso','Somente a data de fabricação'],'A','A seleção deve ser compatível com a classificação de risco e os requisitos aplicáveis ao equipamento.');
// RECEBIMENTO / MONTAGEM / PRESERVAÇÃO
q('Inspeção elétrica','Recebimento e montagem','Recebimento','Conferência','No recebimento de um motor elétrico, é adequado verificar:', ['Identificação, integridade, documentação e requisitos de especificação','Somente a cor','Somente o peso da embalagem','Apenas a corrente nominal','Somente a posição da placa'],'A','Recebimento deve verificar identificação, integridade física, documentos e conformidade com a especificação.');
q('Inspeção elétrica','Recebimento e montagem','Preservação','Objetivo','A preservação de equipamentos elétricos durante armazenamento busca:', ['Evitar deterioração e manter condições adequadas até a instalação','Aumentar a potência nominal','Alterar a classe de isolamento','Substituir a inspeção final','Eliminar a necessidade de ensaios'],'A','Preservação reduz riscos de deterioração por umidade, contaminação, corrosão e outros agentes.');
q('Inspeção elétrica','Recebimento e montagem','Cabos','Instalação','Durante lançamento de cabos, uma preocupação relevante é:', ['Respeitar raio mínimo de curvatura e evitar danos mecânicos','Forçar o cabo até quebrar','Retirar identificações','Desconsiderar o fabricante','Aplicar tensão nominal ao cabo'],'A','Os cabos possuem limites de instalação, incluindo raio de curvatura e esforços mecânicos admissíveis.');
q('Inspeção elétrica','Recebimento e montagem','Terminações','Conexões','Uma conexão elétrica mal torqueada pode causar:', ['Aquecimento localizado e falha de contato','Aumento garantido da isolação','Melhoria do fator de potência','Redução de todas as perdas','Aumento obrigatório da vida útil'],'A','Contato inadequado aumenta resistência de contato e pode provocar aquecimento e deterioração.');
// MÁQUINAS/TESTES
q('Inspeção elétrica','Ensaios','Motor','Isolação','Um valor inadequadamente baixo de resistência de isolamento de um motor pode indicar:', ['Degradação, umidade ou contaminação do isolamento','Aumento da resistência de aterramento apenas','Motor necessariamente novo','Melhor condição dielétrica','Ausência de qualquer risco'],'A','Baixa resistência de isolamento pode indicar condição inadequada do sistema isolante e requer avaliação.');
q('Inspeção elétrica','Ensaios','Motor','Índice de polarização','O índice de polarização de um isolamento compara, de forma geral:', ['Resistências de isolamento medidas em tempos diferentes durante o ensaio','Tensões de duas redes públicas','Duas correntes de partida','Potências ativa e reativa','Duas velocidades do motor'],'A','O índice usa a relação entre a resistência medida em tempos definidos, indicando comportamento do isolamento durante o ensaio.');
q('Inspeção elétrica','Ensaios','Continuidade','Circuito','O teste de continuidade verifica principalmente:', ['A existência de caminho condutivo entre pontos previstos','A potência do motor','A frequência da rede','A resistência de isolamento em alta tensão','O fator de potência'],'A','A continuidade confirma a existência de caminho elétrico conforme esperado.');
q('Inspeção elétrica','Ensaios','Polaridade','Circuitos','A verificação de polaridade busca confirmar:', ['A correta correspondência de terminais/polos em relação ao projeto','A tensão do motor em vazio apenas','A temperatura ambiente','A pintura do painel','O tamanho do cabo'],'A','Polaridade correta assegura conexões conforme a identificação e o funcionamento previsto.');
// COMPLEMENTAR: PORTUGUÊS, MATEMÁTICA, FÍSICA, LÓGICA
q('Básicos','Português','Interpretação','Sentido','Em texto técnico, a compreensão correta de um termo deve considerar prioritariamente:', ['Seu contexto de uso','Somente o significado de dicionário fora do texto','A opinião do leitor','A quantidade de letras','A posição no alfabeto'],'A','Em questões de interpretação, o contexto determina o sentido empregado no texto.','Conteúdo geral de Português — programa PROMINP.');
q('Básicos','Português','Coesão','Conectivos','O conectivo “portanto” introduz normalmente uma ideia de:', ['Conclusão','Oposição','Condição','Causa','Comparação'],'A','“Portanto” é usado para introduzir uma conclusão.','Conteúdo geral de Português — programa PROMINP.');
q('Básicos','Matemática','Porcentagem','Acréscimo','Um equipamento de R$ 2.000 sofre acréscimo de 10%. O novo valor é:', ['R$ 2.010','R$ 2.100','R$ 2.200','R$ 2.500','R$ 3.000'],'C','10% de 2.000 é 200; 2.000+200=2.200.','Conteúdo geral de Matemática — programa PROMINP.');
q('Básicos','Matemática','Proporcionalidade','Regra de três','Se 4 inspetores executam uma atividade em 6 horas, mantendo produtividade constante, 8 inspetores executariam a mesma atividade em:', ['1 h','2 h','3 h','6 h','12 h'],'C','Com dobro de pessoas e mesma produtividade, o tempo cai pela metade: 3 h.','Conteúdo geral de Matemática — programa PROMINP.');
q('Básicos','Matemática','Funções','Linear','Na função y=2x+3, o valor de y para x=4 é:', ['7','8','9','10','11'],'C','y=2·4+3=11. Portanto a alternativa correta é E.','Conteúdo geral de Matemática — programa PROMINP.');
// corrigindo a questão acima: gabarito deve ser E
Q[Q.length-1].gabarito='E';
q('Básicos','Física','Mecânica','Força','Pela segunda lei de Newton, para massa constante, força resultante é:', ['m/a','m·a','a/m','m+a','m−a'],'B','A relação fundamental é F=m·a.','Conteúdo geral de Física — programa PROMINP.');
q('Básicos','Física','Eletricidade','Carga','A unidade SI de carga elétrica é:', ['Ampere','Volt','Coulomb','Ohm','Watt'],'C','A carga elétrica é medida em coulomb (C).','Conteúdo geral de Física — programa PROMINP.');
q('Básicos','Lógica','Proposição','Negação','A negação de “o equipamento está energizado” é:', ['O equipamento não está energizado','O equipamento está muito energizado','O equipamento está funcionando','O equipamento foi inspecionado','O equipamento está aterrado'],'A','A negação lógica de uma proposição simples inverte seu valor lógico: não estar energizado.','Programa de Raciocínio Lógico/diagramação usado em processos técnicos.');
// COMPLEMENTARES DE FORMAÇÃO N1 (qualidade, documentos, controle)
q('Inspeção elétrica','Controle de qualidade','Pontos de inspeção','Hold point','Um hold point em um plano de inspeção representa:', ['Um ponto em que a etapa não deve prosseguir sem a liberação prevista','Uma etapa opcional sem registro','Um intervalo de almoço','Um ponto exclusivo de pintura','Um ensaio destrutivo obrigatório'],'A','Hold point é um ponto de parada/controle definido no plano, com condição de liberação.');
q('Inspeção elétrica','Controle de qualidade','RNC','Não conformidade','Uma não conformidade deve ser registrada quando:', ['Um requisito especificado não é atendido','O inspetor prefere outro modelo','A instalação está conforme','O equipamento chegou antes','O relatório tem capa'],'A','Não conformidade é o não atendimento de um requisito aplicável.');
q('Inspeção elétrica','Controle de qualidade','Rastreabilidade','Identificação','A rastreabilidade de um cabo instalado é favorecida por:', ['Identificação consistente e registros que relacionem origem/destino e documentos','Ausência de etiquetas','Memória do montador','Somente fotografia sem referência','Somente a cor do isolamento'],'A','Identificação e registros documentais permitem acompanhar o item ao longo do processo.');
q('Inspeção elétrica','Controle de qualidade','Documentação','Data book','O data book de um equipamento é usado para reunir:', ['Registros e documentos de qualidade e execução previstos para o item','Somente notas fiscais pessoais','Somente fotos sem identificação','Somente desenhos de arquitetura','Somente registros de RH'],'A','O data book reúne documentação de fabricação, inspeção, testes e rastreabilidade conforme o contrato/projeto.');
q('Inspeção elétrica','Controle de qualidade','Calibração','Instrumentos','Antes de utilizar um instrumento crítico para uma inspeção, deve-se verificar:', ['Identificação e validade/status de calibração aplicáveis','Somente a aparência externa','O fabricante do cabo','A cor do painel','A potência do motor'],'A','O status metrológico do instrumento é parte da confiabilidade do resultado de inspeção.');
// PROVAS E ESTILO
q('Básicos','Inglês técnico','Vocabulário','Electrical','Em documentação técnica, “grounding” significa:', ['Aterramento','Sobrecarga','Iluminação','Resfriamento','Lubrificação'],'A','“Grounding” corresponde a aterramento.','Autoral — vocabulário técnico alinhado ao perfil de leitura técnica do cargo.');
q('Básicos','Inglês técnico','Vocabulário','Insulation','A palavra “insulation” em contexto elétrico significa:', ['Isolação/isolamento','Corrente','Potência','Frequência','Conexão'],'A','“Insulation” corresponde à isolação/isolamento elétrico.','Autoral — vocabulário técnico alinhado ao perfil de leitura técnica do cargo.');
// validações simples
const letters=['A','B','C','D','E'];
for(const x of Q){if(Object.keys(x.alternativas).length!==5)throw Error('Alternativas inválidas '+x.id);if(!letters.includes(x.gabarito))throw Error('Gabarito inválido '+x.id);if(!x.alternativas[x.gabarito])throw Error('Gabarito sem alternativa '+x.id);}
window.INSPETOR_ELETRICA_BANK=Q;
})();
