import { createClient } from 'npm:@supabase/supabase-js@2'
const cors={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'}
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,'Content-Type':'application/json'}})
Deno.serve(async req=>{
 if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({message:'Método não permitido.'},405)
 const auth=req.headers.get('Authorization');if(!auth?.startsWith('Bearer '))return json({message:'Não autenticado.'},401);const token=auth.replace('Bearer ','');const supabaseUrl=Deno.env.get('SUPABASE_URL')!,secretKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'),mpToken=Deno.env.get('MP_ACCESS_TOKEN'),siteUrl=Deno.env.get('SITE_URL');if(!secretKey||!mpToken||!siteUrl)return json({message:'Configuração do servidor incompleta.'},500)
 const admin=createClient(supabaseUrl,secretKey),u=await admin.auth.getUser(token);if(u.error||!u.data.user)return json({message:'Sessão inválida.'},401)
 let body:any;try{body=await req.json()}catch{return json({message:'JSON inválido.'},400)};if(!body.purchase_id)return json({message:'purchase_id é obrigatório.'},400)
 const q=await admin.from('purchases').select('id,user_id,course_id,amount_cents,status,provider_payment_id,billing_mode,metadata').eq('id',body.purchase_id).eq('user_id',u.data.user.id).single();if(q.error||!q.data)return json({message:'Compra não encontrada.'},404);const p=q.data;if(p.status!=='pending')return json({message:'Esta compra não está pendente.'},409);if(p.provider_payment_id)return json({message:'Esta compra já possui pagamento.'},409)
 const c=await admin.from('courses').select('id,name,description,price_cents,active').eq('id',p.course_id).single();if(c.error||!c.data?.active)return json({message:'Curso indisponível.'},400);if(Number(c.data.price_cents||100)!==100||Number(p.amount_cents)!==100)return json({message:'O primeiro mês deve estar configurado em R$ 1,00.'},409)
 const origin=siteUrl.replace(/\/$/,'');const pref={items:[{id:String(c.data.id),title:`Nós Passa — ${c.data.name} — 1º mês`,description:'Primeiro mês por R$ 1,00. Após a autorização da assinatura, renova por R$ 5,90/mês.',quantity:1,currency_id:'BRL',unit_price:1}],external_reference:String(p.id),notification_url:`${supabaseUrl}/functions/v1/payment-webhook`,back_urls:{success:`${origin}/pagamento.html?purchase=${p.id}`,pending:`${origin}/pagamento.html?purchase=${p.id}`,failure:`${origin}/checkout-popular.html?course=${c.data.id}`},auto_return:'approved',payment_methods:{installments:1}};const mp=await fetch('https://api.mercadopago.com/checkout/preferences',{method:'POST',headers:{Authorization:`Bearer ${mpToken}`,'Content-Type':'application/json'},body:JSON.stringify(pref)}),d=await mp.json();if(!mp.ok||!d.id||!d.init_point)return json({message:'Mercado Pago não conseguiu criar o checkout.'},502)
 const metadata={...(p.metadata||{}),payment_flow:'first_month_1_recurring_590',first_month_price_cents:100,recurring_price_cents:590,preference_id:String(d.id)};const up=await admin.from('purchases').update({provider:'mercadopago',billing_mode:'monthly',metadata}).eq('id',p.id);if(up.error)return json({message:'Checkout criado, mas não conseguimos salvar o vínculo.'},500);return json({init_point:d.init_point,preference_id:d.id,billing:'R$ 1,00 no primeiro mês; R$ 5,90/mês a partir do segundo.'})
})
