-- Nós Passa — migração do painel administrativo
-- Preserva a tabela public.profiles e os usuários existentes.
-- Execute este script no Supabase > SQL Editor.

alter table public.profiles add column if not exists role text not null default 'student';
alter table public.profiles add column if not exists active boolean not null default true;
alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists telefone text;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_role_check'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles add constraint profiles_role_check check (role in ('student','admin'));
  end if;
end $$;

update public.profiles p
set email = u.email
from auth.users u
where u.id = p.id and (p.email is null or p.email = '');

create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.user_courses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  status text not null default 'active' check (status in ('active','blocked','expired')),
  purchased_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  unique(user_id, course_id)
);

create table if not exists public.user_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  device_id text not null,
  device_name text,
  ip_address inet,
  user_agent text,
  last_seen timestamptz not null default now(),
  created_at timestamptz not null default now(),
  active boolean not null default true,
  unique(user_id, device_id)
);

alter table public.profiles enable row level security;
alter table public.courses enable row level security;
alter table public.user_courses enable row level security;
alter table public.user_sessions enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin' and active = true
  );
$$;

drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
for select to authenticated
using (id = auth.uid() or public.is_admin());

drop policy if exists profiles_admin_update on public.profiles;
create policy profiles_admin_update on public.profiles
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists profiles_self_update on public.profiles;
create policy profiles_self_update on public.profiles
for update to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists courses_admin_all on public.courses;
create policy courses_admin_all on public.courses
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists user_courses_admin_all on public.user_courses;
create policy user_courses_admin_all on public.user_courses
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists user_sessions_admin_all on public.user_sessions;
create policy user_sessions_admin_all on public.user_sessions
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists user_courses_self_select on public.user_courses;
create policy user_courses_self_select on public.user_courses
for select to authenticated
using (user_id = auth.uid() or public.is_admin());

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, nome, email, telefone, role, active)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'nome', ''),
    new.email,
    coalesce(new.raw_user_meta_data->>'telefone', ''),
    'student',
    true
  )
  on conflict (id) do update
    set email = excluded.email,
        nome = case when excluded.nome <> '' then excluded.nome else public.profiles.nome end,
        telefone = case when excluded.telefone <> '' then excluded.telefone else public.profiles.telefone end;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

insert into public.courses (name, slug, description)
values
  ('ACE Maricá', 'ace-marica', 'Agente de Combate às Endemias — Maricá/RJ.'),
  ('Transpetro', 'transpetro', 'Seleção de cargos e trilhas da Transpetro.'),
  ('Inspetor de Elétrica', 'inspetor-eletrica', 'Preparação para Inspetor de Elétrica.')
on conflict (slug) do nothing;

-- Para transformar sua conta em administrador:
-- update public.profiles set role = 'admin', active = true where id = 'SEU-UUID-AQUI';